const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Fix login bug",
        description:
          "Resolve the issue causing login failures for valid users.",
        date: "2025-05-24",
        category: "development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Update user docs",
        description: "Add new screenshots and explanations to user guide.",
        date: "2025-05-22",
        category: "documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Refactor auth module",
        description: "Simplify the authentication module for maintainability.",
        date: "2025-05-20",
        category: "development",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskStats: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 2,
    firstName: "Sneha",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Create wireframes",
        description: "Design UI mockups for onboarding flow.",
        date: "2025-05-19",
        category: "design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Optimize images",
        description: "Compress and optimize all homepage images.",
        date: "2025-05-18",
        category: "design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Run UI tests",
        description: "Test the layout across different browsers.",
        date: "2025-05-20",
        category: "testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Submit sprint report",
        description: "Summarize tasks and blockers of the current sprint.",
        date: "2025-05-23",
        category: "management",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskStats: {
      active: 2,
      newTask: 2,
      completed: 2,
      failed: 0,
    },
  },
  {
    id: 3,
    firstName: "Karthik",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Set up CI/CD",
        description: "Implement GitHub Actions for testing and deployment.",
        date: "2025-05-16",
        category: "devops",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Dockerize backend",
        description: "Containerize the backend service with Docker.",
        date: "2025-05-24",
        category: "devops",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Patch security flaw",
        description: "Fix vulnerability in JWT verification.",
        date: "2025-05-22",
        category: "security",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Add logging system",
        description: "Implement centralized error and access logs.",
        date: "2025-05-18",
        category: "backend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Review merge requests",
        description: "Code review pending PRs in the repo.",
        date: "2025-05-21",
        category: "development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskStats: {
      active: 2,
      newTask: 2,
      completed: 2,
      failed: 1,
    },
  },
  {
    id: 4,
    firstName: "Meera",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Create test cases",
        description: "Write unit and integration tests for payment module.",
        date: "2025-05-15",
        category: "testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Build analytics dashboard",
        description: "Create UI for displaying user engagement metrics.",
        date: "2025-05-24",
        category: "frontend",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Debug analytics bug",
        description: "Investigate incorrect numbers on dashboard.",
        date: "2025-05-19",
        category: "frontend",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskStats: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 5,
    firstName: "Rohan",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Fix navbar",
        description: "Fix the unresponsive navbar in mobile view.",
        date: "2025-05-20",
        category: "frontend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Add dark mode",
        description: "Implement toggle for light/dark theme.",
        date: "2025-05-23",
        category: "frontend",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Accessibility audit",
        description: "Run audit for screen reader compatibility.",
        date: "2025-05-21",
        category: "frontend",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Fix footer links",
        description: "Broken links in footer need correction.",
        date: "2025-05-22",
        category: "frontend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskStats: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
  },
];

const admin = [
  {
    id: 100,
    firstName: "Neha",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
